"""adding token entity for api authentication

Revision ID: 0bdfc5775438
Revises: ac93c5f594f1
Create Date: 2017-10-16 16:20:37.878311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdfc5775438'
down_revision = 'ac93c5f594f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
