"""Add authorization_token

Revision ID: 106581d34cfd
Revises: 2332756b479a
Create Date: 2018-06-18 11:00:01.371944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106581d34cfd'
down_revision = '2332756b479a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
