"""Added auth_request_id to authentication table

Revision ID: 15f68ac99142
Revises: 914707f4392b
Create Date: 2017-12-11 11:37:26.532784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f68ac99142'
down_revision = '914707f4392b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('auth_request_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authentication', 'auth_request_id')
    # ### end Alembic commands ###
