"""improving service provider linkage

Revision ID: 162f6d63cd9d
Revises: 314fbd1ea5d3
Create Date: 2017-10-17 18:07:54.106835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162f6d63cd9d'
down_revision = '314fbd1ea5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
