"""added validation_server method to authentication

Revision ID: 16a96b5b286b
Revises: 532d2804e2bf
Create Date: 2018-01-18 17:17:20.312263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16a96b5b286b'
down_revision = '532d2804e2bf'
branch_labels = None
depends_on = None
#DROP TYPE AUTHENTICATION_METHOD_ENUM;
#CREATE TYPE AUTHENTICATION_METHOD_ENUM AS ENUM ('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', 'validation_server');

def upgrade():
    #### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('authentication', 'authentication_method',
    #            existing_type=postgresql.ENUM('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', name='authentication_method_enum'),
    #            type_=sa.Enum('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', 'validation_server', name='authentication_method_enum'),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('authentication', 'authentication_method',
    #            existing_type=sa.Enum('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', 'validation_server', name='authentication_method_enum'),
    #            type_=postgresql.ENUM('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', name='authentication_method_enum'),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass