"""adding keystore field to devices

Revision ID: 1ad7cec647f9
Revises: df0e15184c53
Create Date: 2018-04-25 17:54:13.085550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ad7cec647f9'
down_revision = 'df0e15184c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('authentication', 'authentication_session_status',
    #            existing_type=postgresql.ENUM('active', 'inactive', 'expired', 'verifying', 'closed', 'idle', 'walkaway', name='authentication_session_status_enum'),
    #            type_=sa.Enum('active', 'inactive', 'expired', name='authentication_session_status_enum'),
    #            existing_nullable=True)
    # op.add_column('device', sa.Column('keystore', sa.String(), nullable=True))
    # ### end Alembic commands ###
    a=1


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('device', 'keystore')
    # op.alter_column('authentication', 'authentication_session_status',
    #            existing_type=sa.Enum('active', 'inactive', 'expired', name='authentication_session_status_enum'),
    #            type_=postgresql.ENUM('active', 'inactive', 'expired', 'verifying', 'closed', 'idle', 'walkaway', name='authentication_session_status_enum'),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    a=1