"""Add PK to client application

Revision ID: 2332756b479a
Revises: 00ec25ece998
Create Date: 2018-06-12 20:00:25.452718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2332756b479a'
down_revision = '00ec25ece998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_application', sa.Column('application_base_url', sa.String(), nullable=False))
    op.add_column('client_application', sa.Column('application_public_key', sa.String(), nullable=False))
    op.add_column('client_application', sa.Column('server_private_key', sa.String(), nullable=False))
    op.add_column('client_application', sa.Column('server_public_key', sa.String(), nullable=False))
    op.drop_column('client_application', 'user_validation_url')
    op.drop_column('client_application', 'failure_url')
    op.drop_column('client_application', 'success_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_application', sa.Column('success_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client_application', sa.Column('failure_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client_application', sa.Column('user_validation_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('client_application', 'server_public_key')
    op.drop_column('client_application', 'server_private_key')
    op.drop_column('client_application', 'application_public_key')
    op.drop_column('client_application', 'application_base_url')
    # ### end Alembic commands ###
