"""adding keys entity

Revision ID: 2e13af389bbd
Revises: 1ad7cec647f9
Create Date: 2018-04-30 17:54:57.659263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e13af389bbd'
down_revision = '1ad7cec647f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
