"""adding client_application model

Revision ID: 3427e416a594
Revises: bf484f93f16b
Create Date: 2018-06-11 22:11:56.724538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3427e416a594'
down_revision = 'bf484f93f16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_validation_url', sa.String(), nullable=False),
    sa.Column('success_url', sa.String(), nullable=False),
    sa.Column('failure_url', sa.String(), nullable=False),
    sa.Column('css_url', sa.String(), nullable=True),
    sa.Column('client_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_application')
    # ### end Alembic commands ###
