"""adding os field to authentication

Revision ID: 38d48de08283
Revises: 7bb3bc1c2838
Create Date: 2017-10-16 17:11:57.504853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d48de08283'
down_revision = '7bb3bc1c2838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('os', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authentication', 'os')
    # ### end Alembic commands ###
