"""Added additional authentication_status' to authentication table

Revision ID: 4668aeb9cddd
Revises: 15f68ac99142
Create Date: 2017-12-11 15:13:55.575961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '4668aeb9cddd'
down_revision = '15f68ac99142'
branch_labels = None
depends_on = None


# DROP TYPE AUTHENTICATION_STATUS_ENUM;
# CREATE TYPE AUTHENTICATION_STATUS_ENUM AS ENUM ('started', 'notification_sent', 'identification_requested', 'validation_requested', 'completed');


# authentication_status_enum = ENUM('started', 'notification_sent', 'identification_requested', 'validation_requested', 'completed', name='authentication_status_enum', create_type=False)

def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('authentication', 'authentication_status',
    #            existing_type=sa.INTEGER(),
    #            type_=authentication_status_enum,
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('authentication', 'authentication_status',
    #            existing_type=sa.Enum('started', 'notification_sent', 'identification_requested', 'validation_requested', 'completed', name='authentication_status_enum'),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
