"""Added logged_in_at and logged_out_at datetime fields in Authentication Table

Revision ID: 4735b5751171
Revises: 3dda7329a808
Create Date: 2017-12-12 11:52:13.554710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4735b5751171'
down_revision = '3dda7329a808'
branch_labels = None
depends_on = None
#added logged_in_at and logged_out_at columns in the auth table

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('logged_in_at', sa.DateTime(), nullable=True))
    op.add_column('authentication', sa.Column('logged_out_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authentication', 'logged_out_at')
    op.drop_column('authentication', 'logged_in_at')
    # ### end Alembic commands ###
