"""adding missing field to device table, secret

Revision ID: 51ca97150653
Revises: 563360c568bb
Create Date: 2017-10-25 15:50:47.625075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ca97150653'
down_revision = '563360c568bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'secret')
    # ### end Alembic commands ###
