"""added authentication_method, devices and app_version columns to authentication table part2

Revision ID: 532d2804e2bf
Revises: 0826c62231fa
Create Date: 2017-12-14 12:56:08.247471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532d2804e2bf'
down_revision = '0826c62231fa'
branch_labels = None
depends_on = None

#CREATE TYPE AUTHENTICATION_METHOD_ENUM AS ENUM ('manual', 'bluetooth', 'geolocation', 'sonic', 'facial');


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('app_version', sa.String(), nullable=True))
    op.add_column('authentication', sa.Column('authentication_method', sa.Enum('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', name='authentication_method_enum'), nullable=True))
    op.add_column('authentication', sa.Column('devices', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authentication', 'devices')
    op.drop_column('authentication', 'authentication_method')
    op.drop_column('authentication', 'app_version')
    # ### end Alembic commands ###
