"""authnetication enums to integers

Revision ID: 563360c568bb
Revises: fa6f1a71cbfc
Create Date: 2017-10-19 17:05:15.265364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '563360c568bb'
down_revision = 'fa6f1a71cbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authentication', 'authentication_result',
               existing_type=postgresql.ENUM('allowed', 'denied', name='authentication_result_enum'),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('authentication', 'authentication_status',
               existing_type=postgresql.ENUM('started', 'inprogress', 'completed', name='authentication_status_enum'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authentication', 'authentication_status',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('started', 'inprogress', 'completed', name='authentication_status_enum'),
               existing_nullable=True)
    op.alter_column('authentication', 'authentication_result',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('allowed', 'denied', name='authentication_result_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###
