"""Adding registration Status

Revision ID: 6b7c2287204c
Revises: 75f841f23d56
Create Date: 2017-11-27 17:00:41.511674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM



# revision identifiers, used by Alembic.
revision = '6b7c2287204c'
down_revision = '75f841f23d56'
branch_labels = None
depends_on = None


registration_status_enum = ENUM('started', 'installed', 'inprogress', 'expired', 'invalid', 'completed', name='registration_status_enum', create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
