"""adding token entity for api authentication

Revision ID: 6bf240573a1b
Revises: 0bdfc5775438
Create Date: 2017-10-16 16:21:46.145624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf240573a1b'
down_revision = '0bdfc5775438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
