"""migration

Revision ID: 756c3e66edca
Revises: 0a3f95addd20
Create Date: 2021-01-31 18:01:23.038802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756c3e66edca'
down_revision = '0a3f95addd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('is_account_contact', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), server_default='Default', nullable=True),
    sa.Column('emailaddress', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('keys_status', sa.Enum('ok', 'invalid', name='keys_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postal_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('address_1', sa.String(), nullable=False),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_notification_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('apns_certificate_uri', sa.String(), nullable=True),
    sa.Column('use_apns_sandbox', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('fcm_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('authentication_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentication_url')
    )
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.String(), server_default=FetchedValue(), nullable=False),
    sa.Column('account_status', sa.Enum('active', 'disabled', name='account_status_enum'), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('account_group_id', sa.Integer(), nullable=True),
    sa.Column('push_notification_certificate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_group_id'], ['account_group.id'], ),
    sa.ForeignKeyConstraint(['push_notification_certificate_id'], ['push_notification_certificate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contact_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_postal_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('postal_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postal_address_id'], ['postal_address.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('telephone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telephone_id'], ['telephone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(), nullable=True),
    sa.Column('registration_status', sa.Enum('started', 'installed', 'inprogress', 'expired', 'invalid', 'completed', name='registration_status_enum'), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('push_notification_token', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('keystore', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('service_credentials', sa.DateTime(), nullable=True),
    sa.Column('push_notification_certificate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['push_notification_certificate_id'], ['push_notification_certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('application_base_url', sa.String(), nullable=False),
    sa.Column('application_public_key', sa.String(), nullable=False),
    sa.Column('server_public_key', sa.String(), nullable=False),
    sa.Column('server_private_key', sa.String(), nullable=False),
    sa.Column('css_url', sa.String(), nullable=True),
    sa.Column('client_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('user_registration_status', sa.Enum('started', 'email_sent', 'email_verified', 'completed', 'admin_disable', 'user_disable', 'account_cancelled', 'expired', 'deleted', name='user_registration_status_enum'), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('has_facial_images', sa.Boolean(), nullable=True),
    sa.Column('facial_storage_prefix', sa.String(), nullable=True),
    sa.Column('idtoken', sa.String(), nullable=True),
    sa.Column('secret1', sa.String(), nullable=True),
    sa.Column('secret2', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'account_id', name='account_id_username_key')
    )
    op.create_table('authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_request_id', sa.String(), nullable=True),
    sa.Column('authentication_status', sa.Enum('started', 'notification_sent', 'identification_requested', 'validation_requested', 'completed', 'identification_started', 'identification_confirmed', name='authentication_status_enum'), nullable=True),
    sa.Column('authentication_result', sa.Enum('allowed', 'denied', 'failed', name='authentication_result_enum'), nullable=True),
    sa.Column('authentication_session_status', sa.Enum('active', 'inactive', 'expired', 'verifying', 'closed', 'idle', 'walkaway', name='authentication_session_status_enum'), nullable=True),
    sa.Column('authentication_method', sa.Enum('manual', 'bluetooth', 'geolocation', 'sonic', 'facial', 'validation_server', name='authentication_method_enum'), nullable=True),
    sa.Column('authentication_status_secret', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('devices', sa.String(), nullable=True),
    sa.Column('browser_device', sa.String(), nullable=True),
    sa.Column('mobile_device', sa.String(), nullable=True),
    sa.Column('desktop_device', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('useragent', sa.String(), nullable=True),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('geolocation', sa.String(), nullable=True),
    sa.Column('ble_mobile', sa.String(), nullable=True),
    sa.Column('ble_desktop', sa.String(), nullable=True),
    sa.Column('walkaway_data', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('push_notification_certificate_id', sa.Integer(), nullable=True),
    sa.Column('logged_in_at', sa.DateTime(), nullable=True),
    sa.Column('logged_out_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['push_notification_certificate_id'], ['push_notification_certificate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorization_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('authorization_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['client_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_status', sa.Enum('new', 'inuse', 'expired', 'deleted', name='token_status_enum'), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_service_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('service_provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['service_provider_id'], ['service_provider.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tag')
    op.drop_table('user_group_service_provider')
    op.drop_table('user_device')
    op.drop_table('token')
    op.drop_table('authorization_token')
    op.drop_table('authentication')
    op.drop_table('user')
    op.drop_table('client_application')
    op.drop_table('account_tag')
    op.drop_table('device')
    op.drop_table('contact_telephone')
    op.drop_table('contact_postal_address')
    op.drop_table('contact_email')
    op.drop_table('account')
    op.drop_table('telephone')
    op.drop_table('service_provider')
    op.drop_table('push_notification_certificate')
    op.drop_table('postal_address')
    op.drop_table('keys')
    op.drop_table('group')
    op.drop_table('email')
    op.drop_table('contact')
    op.drop_table('account_group')
    # ### end Alembic commands ###
