"""fixing device registration status choicetype

Revision ID: 75f841f23d56
Revises: 911dbb87134e
Create Date: 2017-11-24 21:07:08.008563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f841f23d56'
down_revision = '911dbb87134e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
