"""adding push notification certificate to authentication

Revision ID: 86b5f3b95852
Revises: 38d48de08283
Create Date: 2017-10-16 18:04:42.567733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b5f3b95852'
down_revision = '38d48de08283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('push_notification_certificate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authentication', 'push_notification_certificate', ['push_notification_certificate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authentication', type_='foreignkey')
    op.drop_column('authentication', 'push_notification_certificate_id')
    # ### end Alembic commands ###
