"""working on desktop device registration

Revision ID: 8f7b487d643c
Revises: 6b7c2287204c
Create Date: 2017-12-05 12:21:01.862203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7b487d643c'
down_revision = '6b7c2287204c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
