"""improving device registration

Revision ID: 911dbb87134e
Revises: ea67f64532cb
Create Date: 2017-11-22 10:57:33.373336

"""
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '911dbb87134e'
down_revision = 'ea67f64532cb'
branch_labels = None
depends_on = None

# added manually into database
# CREATE TYPE REGISTRATION_STATUS_ENUM AS ENUM ('started', 'inprogress', 'expired', 'invalid', 'completed');

registration_status_enum = ENUM('started', 'inprogress', 'expired', 'invalid', 'completed', name='registration_status_enum', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('app_version', sa.String(), nullable=True))
    op.add_column('device', sa.Column('registration_status', registration_status_enum, nullable=True))
    op.add_column('device', sa.Column('service_credentials', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'service_credentials')
    op.drop_column('device', 'registration_status')
    op.drop_column('device', 'app_version')
    # ### end Alembic commands ###
