"""removed unique key constraints from UserDevice table

Revision ID: 914707f4392b
Revises: bd6a4159e705
Create Date: 2017-12-08 11:26:59.149618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914707f4392b'
down_revision = 'bd6a4159e705'
branch_labels = None
depends_on = None
# ALTER TABLE public.user_device DROP CONSTRAINT user_device_user_id_key;
# ALTER TABLE public.user_device DROP CONSTRAINT user_device_device_id_key;

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
