"""add push cert to device

Revision ID: ac1249a31c8e
Revises: 8f7b487d643c
Create Date: 2017-12-06 10:39:10.846118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1249a31c8e'
down_revision = '8f7b487d643c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('push_notification_certificate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'push_notification_certificate', ['push_notification_certificate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'push_notification_certificate_id')
    # ### end Alembic commands ###
