"""start

Revision ID: ac93c5f594f1
Revises: ae7910e3b3f8
Create Date: 2017-10-13 18:03:06.258336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'ac93c5f594f1'
down_revision = 'ae7910e3b3f8'
branch_labels = None
depends_on = None

authentication_status_enum = ENUM('started', 'inprogress', 'completed', name='authentication_status_enum', create_type=False)
authentication_result_enum = ENUM('allowed', 'denied', name='authentication_result_enum', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authentication_status', authentication_status_enum, nullable=True),
    sa.Column('authentication_result', authentication_result_enum, nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('useragent', sa.String(), nullable=True),
    sa.Column('geolocation', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentication')
    # ### end Alembic commands ###
