"""added Hubs

Revision ID: b4aaea4185ac
Revises: 0a3f95addd20
Create Date: 2021-02-04 18:34:38.161962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aaea4185ac'
down_revision = '0a3f95addd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'facial_storage_prefix')
    op.drop_column('user', 'has_facial_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_facial_images', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('facial_storage_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
