"""add device type push cert

Revision ID: bd6a4159e705
Revises: ac1249a31c8e
Create Date: 2017-12-06 12:17:37.467975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType
from hubub_common.models._types import DeviceType

# revision identifiers, used by Alembic.
revision = 'bd6a4159e705'
down_revision = 'ac1249a31c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_notification_certificate', sa.Column('type', sa.String(), nullable=True))
    op.drop_constraint('user_push_notification_certificate_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'push_notification_certificate_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('push_notification_certificate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_push_notification_certificate_id_fkey', 'user', 'push_notification_certificate', ['push_notification_certificate_id'], ['id'])
    op.drop_column('push_notification_certificate', 'type')
    # ### end Alembic commands ###
