"""adding new authentication_status of identification_confirmed

Revision ID: df0e15184c53
Revises: 16a96b5b286b
Create Date: 2018-02-05 16:49:56.528210

"""
from alembic import op
import sqlalchemy as sa

#ALTER TYPE AUTHENTICATION_STATUS_ENUM ADD VALUE 'identification_confirmed' AFTER 'identification_started';
# revision identifiers, used by Alembic.
revision = 'df0e15184c53'
down_revision = '16a96b5b286b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
