"""creating device upon registration, removing required fields

Revision ID: e2726cae9992
Revises: 51ca97150653
Create Date: 2017-11-06 15:26:57.266348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2726cae9992'
down_revision = '51ca97150653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
