"""Add authorization_token for real

Revision ID: e6f8e9823986
Revises: 106581d34cfd
Create Date: 2018-06-18 12:22:13.976468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f8e9823986'
down_revision = '106581d34cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('authorization_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['client_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorization_token')
    # ### end Alembic commands ###
