"""catch-up with model

Revision ID: ea67f64532cb
Revises: e2726cae9992
Create Date: 2017-11-08 15:15:30.927957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea67f64532cb'
down_revision = 'e2726cae9992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
