"""Added walkaway field to track amount of walkaways

Revision ID: efb6f5aee0cf
Revises: e6f8e9823986
Create Date: 2018-07-10 19:14:51.518698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efb6f5aee0cf'
down_revision = 'e6f8e9823986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys_copy1')
    op.add_column('authentication', sa.Column('walkaway_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authentication', 'walkaway_data')
    op.create_table('keys_copy1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('private_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keys_status', postgresql.ENUM('ok', 'invalid', name='keys_status_enum'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('invalidated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='keys_copy1_pkey')
    )
    # ### end Alembic commands ###
