"""adding primary user flag

Revision ID: fa6f1a71cbfc
Revises: 162f6d63cd9d
Create Date: 2017-10-19 15:20:07.529052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6f1a71cbfc'
down_revision = '162f6d63cd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_primary')
    # ### end Alembic commands ###
